# Generated by Django 4.1 on 2022-08-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='profesion',
            field=models.CharField(max_length=50),
        ),
    ]
